export const WORKER_FETCH_REQUESTS_BEGIN = 'WORKER_FETCH_REQUESTS_BEGIN';
export const WORKER_FETCH_REQUESTS_SUCCESS = 'WORKER_FETCH_REQUESTS_SUCCESS';
export const WORKER_FETCH_REQUESTS_FAILURE = 'WORKER_FETCH_REQUESTS_FAILURE';
export const WORKER_FETCH_REQUESTS_DISMISS_ERROR = 'WORKER_FETCH_REQUESTS_DISMISS_ERROR';
