export const ADMIN_CREATE_REQUEST_BEGIN = 'ADMIN_CREATE_REQUEST_BEGIN';
export const ADMIN_CREATE_REQUEST_SUCCESS = 'ADMIN_CREATE_REQUEST_SUCCESS';
export const ADMIN_CREATE_REQUEST_FAILURE = 'ADMIN_CREATE_REQUEST_FAILURE';
export const ADMIN_CREATE_REQUEST_DISMISS_ERROR = 'ADMIN_CREATE_REQUEST_DISMISS_ERROR';
export const ADMIN_FETCH_USERS_BEGIN = 'ADMIN_FETCH_USERS_BEGIN';
export const ADMIN_FETCH_USERS_SUCCESS = 'ADMIN_FETCH_USERS_SUCCESS';
export const ADMIN_FETCH_USERS_FAILURE = 'ADMIN_FETCH_USERS_FAILURE';
export const ADMIN_FETCH_USERS_DISMISS_ERROR = 'ADMIN_FETCH_USERS_DISMISS_ERROR';
